SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [Sigma].[DESPACHOS_CARGA_ACTUAL] (
		[BASEDATOS]          [varchar](100) COLLATE Modern_Spanish_CI_AS NULL,
		[CODIGODESPACHO]     [varchar](4) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [Sigma].[DESPACHOS_CARGA_ACTUAL] SET (LOCK_ESCALATION = TABLE)
GO
